#!/usr/bin/env bash

# This installer will:
# 1. Detect the target platform, and download the appropriate distribution
# 2. Copy the distribution to the bin directory as `download-secure-files`
# 3. Make `download-secure-files` executable
# 4. Run `dowload-secure-files`
# Please note:
# * This will only work on Linux and macOS systems
# * curl is required

os_name=$(uname -s | tr "[:upper:]" "[:lower:]")

architecture=""
case $(uname -m) in
    i386)   architecture="386" ;;
    i686)   architecture="386" ;;
    x86_64) architecture="amd64" ;;
    aarch64) architecture="arm64" ;;
    arm64)  architecture="arm64" ;;
    arm)    architecture="arm" ;;
    *)   echo "Unable to determine system architecture."; exit 1 ;;
esac

current_path=$(pwd)

bin_filename="download-secure-files-${os_name}-${architecture}"

download_url="https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/releases/permalink/latest/downloads/${bin_filename}"

bin_dir=$1
if [ "$bin_dir" == "" ]; then
  if [[ $EUID -ne 0 ]]; then
    bin_dir="$HOME/bin"
  else
    bin_dir="/usr/bin"
  fi
fi

display_error() {
  tput sgr0
  tput setaf 1
  echo "ERROR: $1"
  tput sgr0
  exit 1
}

[ "$bin_dir" == "" ] && display_error "No destination specified!"
[ -d $bin_dir ] || mkdir -p $bin_dir > /dev/null 2>&1 || display_error "Failed to create $bin_dir"
[ -z `which curl` ] && display_error "Could not find curl"

tmp_dir=${TMPDIR:-/tmp}
download_dir="$tmp_dir"
download_file=${tmp_dir}/${bin_filename}

echo "Downloading download-secure-files from ${download_url}"
curl -sS -k -L -H "Accept: application/octet-stream" $download_url -o ${download_file}

cd $bin_dir
if [[ ! -f ${download_file} ]]; then
    echo "Failed to download file"
    exit 1
fi

echo "Installing download-secure-files at ${bin_dir}/download-secure-files"
mv $download_file $bin_dir/download-secure-files

cd $current_path

chmod +x $bin_dir/download-secure-files
$bin_dir/download-secure-files
